### ISSUE TITLE
[enhancement] be able to re-order songs on a playlist

### ISSUE THREAD

**Issue by martomato** [CagedNicolas/Sadboi#1]
maybe want to edit an existing playlist, being able to move songs up/down/to specific positions within a playlist would be neato

**Comment by CagedNicolas** [comment]
Thanks for the input! Has been added to development plan and will work on it soon (:

**Comment by CagedNicolas** [comment]
You now can move songs up/down in a specified playlist. Ability to move them to specific positions will be added later down the line; for now I'll concentrate on building the basic commands and making sure everything works as intended before adding complexity to them.
